# Generated by Django 4.2.7 on 2024-11-03 09:51

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_picture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to=pictures.models.user_directory_path),
        ),
    ]
